package basic.webapp.utilities

import basic.fantasy.backgrounds.BackgroundGenerator._
import basic.fantasy.backgrounds.CharacterAlignments._
import basic.fantasy.backgrounds.{BackgroundGenerator, CharacterAlignments, Races}
import basic.fantasy.backgrounds.Races._
import basic.fantasy.characterclass.CharacterClasses._
import basic.fantasy.characterclass.KiPowers._
import basic.fantasy.characterclass.{CharacterClasses, KiPowers, SavingsThrows}
import basic.fantasy.equipment.Armors._
import basic.fantasy.equipment.{Armors, Equipment, EquipmentPacks, MagicalItems, Shields}
import basic.fantasy.equipment.EquipmentPacks._
import basic.fantasy.equipment.MagicalItems._
import basic.fantasy.equipment.MeleeWeapons._
import basic.fantasy.equipment.RangedWeapons._
import basic.fantasy.equipment.Shields._
import basic.webapp.CharacterState
import upickle.default


object Serializers {

  implicit val dwarfRW: default.ReadWriter[Races.Dwarf.type] = upickle.default.macroRW[Dwarf.type]
  implicit val elfRW: default.ReadWriter[Races.Elf.type] = upickle.default.macroRW[Elf.type]
  implicit val halfElfRW: default.ReadWriter[Races.HalfElf.type] = upickle.default.macroRW[HalfElf.type]
  implicit val halfOrcRW: default.ReadWriter[Races.HalfOrc.type] = upickle.default.macroRW[HalfOrc.type]
  implicit val halflingRW: default.ReadWriter[Races.Halfling.type] = upickle.default.macroRW[Halfling.type]
  implicit val humanRW: default.ReadWriter[Races.Human.type] = upickle.default.macroRW[Human.type]
  implicit val raceRW: default.ReadWriter[Race] = upickle.default.macroRW[Race]

  implicit val clericRW: default.ReadWriter[CharacterClasses.Cleric.type] = upickle.default.macroRW[Cleric.type]
  implicit val fighterRW: default.ReadWriter[CharacterClasses.Fighter.type] = upickle.default.macroRW[Fighter.type]
  implicit val fighterMagicUserRW: default.ReadWriter[CharacterClasses.FighterMagicUser.type] = upickle.default.macroRW[FighterMagicUser.type]
  implicit val magicUserRW: default.ReadWriter[CharacterClasses.MagicUser.type] = upickle.default.macroRW[MagicUser.type]
  implicit val magicUserThiefRW: default.ReadWriter[CharacterClasses.MagicUserThief.type] = upickle.default.macroRW[MagicUserThief.type]
  implicit val monkRW: default.ReadWriter[CharacterClasses.Monk.type] = upickle.default.macroRW[Monk.type]
  implicit val thiefRW: default.ReadWriter[CharacterClasses.Thief.type] = upickle.default.macroRW[Thief.type]
  implicit val classRW: default.ReadWriter[CharacterClass] = upickle.default.macroRW[CharacterClass]

  implicit val chaoticRW: default.ReadWriter[CharacterAlignments.Chaotic.type] = upickle.default.macroRW[Chaotic.type]
  implicit val lawfulRW: default.ReadWriter[CharacterAlignments.Lawful.type] = upickle.default.macroRW[Lawful.type]
  implicit val neutralRW: default.ReadWriter[CharacterAlignments.Neutral.type] = upickle.default.macroRW[Neutral.type]
  implicit val alignmentRW: default.ReadWriter[CharacterAlignment] = upickle.default.macroRW[CharacterAlignment]

  implicit val savingsThrowsRW: default.ReadWriter[SavingsThrows] = upickle.default.macroRW[SavingsThrows]

  implicit val alfheimRW: default.ReadWriter[BackgroundGenerator.Alfheim.type] = upickle.default.macroRW[Alfheim.type]
  implicit val alphatiaRW: default.ReadWriter[BackgroundGenerator.Alphatia.type] = upickle.default.macroRW[Alphatia.type]
  implicit val altruaghinRW: default.ReadWriter[BackgroundGenerator.Altruaghin.type] = upickle.default.macroRW[Altruaghin.type]
  implicit val darokinRW: default.ReadWriter[BackgroundGenerator.Darokin.type] = upickle.default.macroRW[Darokin.type]
  implicit val ethengarRW: default.ReadWriter[BackgroundGenerator.Ethengar.type] = upickle.default.macroRW[Ethengar.type]
  implicit val fiveShiresRW: default.ReadWriter[BackgroundGenerator.FiveShires.type] = upickle.default.macroRW[FiveShires.type]
  implicit val glantriRW: default.ReadWriter[BackgroundGenerator.Glantri.type] = upickle.default.macroRW[Glantri.type]
  implicit val ierendiRW: default.ReadWriter[BackgroundGenerator.Ierendi.type] = upickle.default.macroRW[Ierendi.type]
  implicit val karameikosRW: default.ReadWriter[BackgroundGenerator.Karameikos.type] = upickle.default.macroRW[Karameikos.type]
  implicit val minrothadRW: default.ReadWriter[BackgroundGenerator.Minrothad.type] = upickle.default.macroRW[Minrothad.type]
  implicit val northernReachesRW: default.ReadWriter[BackgroundGenerator.NorthernReaches.type] = upickle.default.macroRW[NorthernReaches.type]
  implicit val rockhomeRW: default.ReadWriter[BackgroundGenerator.Rockhome.type] = upickle.default.macroRW[Rockhome.type]
  implicit val shadowLandsRW: default.ReadWriter[BackgroundGenerator.ShadowLands.type] = upickle.default.macroRW[ShadowLands.type]
  implicit val tharRW: default.ReadWriter[BackgroundGenerator.Thar.type] = upickle.default.macroRW[Thar.type]
  implicit val thyatisRW: default.ReadWriter[BackgroundGenerator.Thyatis.type] = upickle.default.macroRW[Thyatis.type]
  implicit val wildlandsRW: default.ReadWriter[BackgroundGenerator.Wildlands.type] = upickle.default.macroRW[Wildlands.type]
  implicit val ylaruamRW: default.ReadWriter[BackgroundGenerator.Ylaruam.type] = upickle.default.macroRW[Ylaruam.type]
  implicit val nationalityRW: default.ReadWriter[Nationality] = upickle.default.macroRW[Nationality]
  implicit val backgroundRW: default.ReadWriter[Background] = upickle.default.macroRW[Background]

  implicit val bandedMailRW: default.ReadWriter[BandedMail] = upickle.default.macroRW[BandedMail]
  implicit val brigandineRW: default.ReadWriter[Brigandine] = upickle.default.macroRW[Brigandine]
  implicit val chainMailRW: default.ReadWriter[ChainMail] = upickle.default.macroRW[ChainMail]
  implicit val fieldPlateMailRW: default.ReadWriter[FieldPlateMail] = upickle.default.macroRW[FieldPlateMail]
  implicit val fullPlateMailRW: default.ReadWriter[FullPlateMail] = upickle.default.macroRW[FullPlateMail]
  implicit val hideRW: default.ReadWriter[Armors.Hide.type] = upickle.default.macroRW[Hide.type]
  implicit val leatherRW: default.ReadWriter[Leather] = upickle.default.macroRW[Leather]
  implicit val noArmorRW: default.ReadWriter[Armors.NoArmor.type] = upickle.default.macroRW[NoArmor.type]
  implicit val paddedRW: default.ReadWriter[Armors.Padded.type] = upickle.default.macroRW[Padded.type]
  implicit val plateMailRW: default.ReadWriter[PlateMail] = upickle.default.macroRW[PlateMail]
  implicit val ringMailRW: default.ReadWriter[RingMail] = upickle.default.macroRW[RingMail]
  implicit val scaleMailRW: default.ReadWriter[ScaleMail] = upickle.default.macroRW[ScaleMail]
  implicit val splintMailRW: default.ReadWriter[SplintMail] = upickle.default.macroRW[SplintMail]
  implicit val studdedRW: default.ReadWriter[Studded] = upickle.default.macroRW[Studded]
  implicit val armorRW: default.ReadWriter[Armor] = upickle.default.macroRW[Armor]

  implicit val bucklerRW: default.ReadWriter[Buckler] = upickle.default.macroRW[Buckler]
  implicit val mediumShieldRW: default.ReadWriter[MediumShield] = upickle.default.macroRW[MediumShield]
  implicit val noShieldRW: default.ReadWriter[Shields.NoShield.type] = upickle.default.macroRW[NoShield.type]
  implicit val towerShieldRW: default.ReadWriter[TowerShield] = upickle.default.macroRW[TowerShield]
  implicit val shieldRW: default.ReadWriter[Shield] = upickle.default.macroRW[Shield]

  implicit val battleAxeRW: default.ReadWriter[BattleAxe] = upickle.default.macroRW[BattleAxe]
  implicit val blackjackRW: default.ReadWriter[Blackjack] = upickle.default.macroRW[Blackjack]
  implicit val chainRW: default.ReadWriter[Chain] = upickle.default.macroRW[Chain]
  implicit val clubRW: default.ReadWriter[Club] = upickle.default.macroRW[Club]
  implicit val cudgelRW: default.ReadWriter[Cudgel] = upickle.default.macroRW[Cudgel]
  implicit val cutlassRW: default.ReadWriter[Cutlass] = upickle.default.macroRW[Cutlass]
  implicit val daggerRW: default.ReadWriter[Dagger] = upickle.default.macroRW[Dagger]
  implicit val defendingDaggerRW: default.ReadWriter[DefendingDagger] = upickle.default.macroRW[DefendingDagger]
  implicit val flailRW: default.ReadWriter[Flail] = upickle.default.macroRW[Flail]
  implicit val footmansPickRW: default.ReadWriter[FootmansPick] = upickle.default.macroRW[FootmansPick]
  implicit val greatAxeRW: default.ReadWriter[GreatAxe] = upickle.default.macroRW[GreatAxe]
  implicit val greatClubRW: default.ReadWriter[GreatClub] = upickle.default.macroRW[GreatClub]
  implicit val greatFlailRW: default.ReadWriter[GreatFlail] = upickle.default.macroRW[GreatFlail]
  implicit val greatMaceRW: default.ReadWriter[GreatMace] = upickle.default.macroRW[GreatMace]
  implicit val handAxeRW: default.ReadWriter[HandAxe] = upickle.default.macroRW[HandAxe]
  implicit val hookRW: default.ReadWriter[Hook] = upickle.default.macroRW[Hook]
  implicit val lightMaceRW: default.ReadWriter[LightMace] = upickle.default.macroRW[LightMace]
  implicit val longSwordRW: default.ReadWriter[LongSword] = upickle.default.macroRW[LongSword]
  implicit val maceRW: default.ReadWriter[Mace] = upickle.default.macroRW[Mace]
  implicit val maulRW: default.ReadWriter[Maul] = upickle.default.macroRW[Maul]
  implicit val militaryPickRW: default.ReadWriter[MilitaryPick] = upickle.default.macroRW[MilitaryPick]
  implicit val morningstarRW: default.ReadWriter[Morningstar] = upickle.default.macroRW[Morningstar]
  implicit val poleArmRW: default.ReadWriter[PoleArm] = upickle.default.macroRW[PoleArm]
  implicit val quarterStaffRW: default.ReadWriter[QuarterStaff] = upickle.default.macroRW[QuarterStaff]
  implicit val sapRW: default.ReadWriter[Sap] = upickle.default.macroRW[Sap]
  implicit val scimitarRW: default.ReadWriter[Scimitar] = upickle.default.macroRW[Scimitar]
  implicit val scytheRW: default.ReadWriter[Scythe] = upickle.default.macroRW[Scythe]
  implicit val shortSwordRW: default.ReadWriter[ShortSword] = upickle.default.macroRW[ShortSword]
  implicit val sickleRW: default.ReadWriter[Sickle] = upickle.default.macroRW[Sickle]
  implicit val silverDaggerRW: default.ReadWriter[SilverDagger] = upickle.default.macroRW[SilverDagger]
  implicit val spearRW: default.ReadWriter[Spear] = upickle.default.macroRW[Spear]
  implicit val tridentRW: default.ReadWriter[Trident] = upickle.default.macroRW[Trident]
  implicit val twoHandedSwordRW: default.ReadWriter[TwoHandedSword] = upickle.default.macroRW[TwoHandedSword]
  implicit val unarmedRW: default.ReadWriter[Unarmed] = upickle.default.macroRW[Unarmed]
  implicit val walkingStaffRW: default.ReadWriter[WalkingStaff] = upickle.default.macroRW[WalkingStaff]
  implicit val warHammerRW: default.ReadWriter[WarHammer] = upickle.default.macroRW[WarHammer]
  implicit val whipRW: default.ReadWriter[Whip] = upickle.default.macroRW[Whip]
  implicit val meleeWeaponRW: default.ReadWriter[MeleeWeapon] = upickle.default.macroRW[MeleeWeapon]

  implicit val arrowRW: default.ReadWriter[Arrow] = upickle.default.macroRW[Arrow]
  implicit val bulletRW: default.ReadWriter[Bullet] = upickle.default.macroRW[Bullet]
  implicit val dartAmmoRW: default.ReadWriter[DartAmmo] = upickle.default.macroRW[DartAmmo]
  implicit val quarrelRW: default.ReadWriter[Quarrel] = upickle.default.macroRW[Quarrel]
  implicit val silverArrowRW: default.ReadWriter[SilverArrow] = upickle.default.macroRW[SilverArrow]
  implicit val silverBulletRW: default.ReadWriter[SilverBullet] = upickle.default.macroRW[SilverBullet]
  implicit val silverQuarrelRW: default.ReadWriter[SilverQuarrel] = upickle.default.macroRW[SilverQuarrel]
  implicit val stoneRW: default.ReadWriter[Stone] = upickle.default.macroRW[Stone]
  implicit val ammoRW: default.ReadWriter[Ammo] = upickle.default.macroRW[Ammo]

  implicit val blowgunRW: default.ReadWriter[Blowgun] = upickle.default.macroRW[Blowgun]
  implicit val bolaRW: default.ReadWriter[Bola] = upickle.default.macroRW[Bola]
  implicit val dartRW: default.ReadWriter[Dart] = upickle.default.macroRW[Dart]
  implicit val handCrossbowRW: default.ReadWriter[HandCrossbow] = upickle.default.macroRW[HandCrossbow]
  implicit val heavyCrossbowRW: default.ReadWriter[HeavyCrossbow] = upickle.default.macroRW[HeavyCrossbow]
  implicit val javelinRW: default.ReadWriter[Javelin] = upickle.default.macroRW[Javelin]
  implicit val lightCrossbowRW: default.ReadWriter[LightCrossbow] = upickle.default.macroRW[LightCrossbow]
  implicit val longBowRW: default.ReadWriter[LongBow] = upickle.default.macroRW[LongBow]
  implicit val shortBowRW: default.ReadWriter[ShortBow] = upickle.default.macroRW[ShortBow]
  implicit val slingRW: default.ReadWriter[Sling] = upickle.default.macroRW[Sling]
  implicit val throwingKnifeRW: default.ReadWriter[ThrowingKnife] = upickle.default.macroRW[ThrowingKnife]
  implicit val rangedWeaponRW: default.ReadWriter[RangedWeapon] = upickle.default.macroRW[RangedWeapon]

  implicit val burglarsPackRW: default.ReadWriter[EquipmentPacks.BurglarsPack.type] = upickle.default.macroRW[BurglarsPack.type]
  implicit val dungeoneersPackRW: default.ReadWriter[EquipmentPacks.DungeoneersPack.type] = upickle.default.macroRW[DungeoneersPack.type]
  implicit val explorersPackRW: default.ReadWriter[EquipmentPacks.ExplorersPack.type] = upickle.default.macroRW[ExplorersPack.type]
  implicit val priestsPackRW: default.ReadWriter[EquipmentPacks.PriestsPack.type] = upickle.default.macroRW[PriestsPack.type]
  implicit val scholarBurglarsPackRW: default.ReadWriter[EquipmentPacks.ScholarBurglarsPack.type] = upickle.default.macroRW[ScholarBurglarsPack.type]
  implicit val scholarExplorersPackRW: default.ReadWriter[EquipmentPacks.ScholarExplorersPack.type] = upickle.default.macroRW[ScholarExplorersPack.type]
  implicit val scholarsPackRW: default.ReadWriter[EquipmentPacks.ScholarsPack.type] = upickle.default.macroRW[ScholarsPack.type]
  implicit val equipmentPackRW: default.ReadWriter[EquipmentPack] = upickle.default.macroRW[EquipmentPack]

  implicit val amuletOfProofAgainstDetectionAndLocationRW: default.ReadWriter[MagicalItems.AmuletOfProofAgainstDetectionAndLocation.type] = upickle.default.macroRW[AmuletOfProofAgainstDetectionAndLocation.type]
  implicit val bagOfDevouringRW: default.ReadWriter[MagicalItems.BagOfDevouring.type] = upickle.default.macroRW[BagOfDevouring.type]
  implicit val bagOfHoldingRW: default.ReadWriter[MagicalItems.BagOfHolding.type] = upickle.default.macroRW[BagOfHolding.type]
  implicit val bootsOfLevitationRW: default.ReadWriter[MagicalItems.BootsOfLevitation.type] = upickle.default.macroRW[BootsOfLevitation.type]
  implicit val bootsOfSpeedRW: default.ReadWriter[MagicalItems.BootsOfSpeed.type] = upickle.default.macroRW[BootsOfSpeed.type]
  implicit val bootsOfTravelingAndLeapingRW: default.ReadWriter[MagicalItems.BootsOfTravelingAndLeaping.type] = upickle.default.macroRW[BootsOfTravelingAndLeaping.type]
  implicit val bowlCommandingWaterElementalsRW: default.ReadWriter[MagicalItems.BowlCommandingWaterElementals.type] = upickle.default.macroRW[BowlCommandingWaterElementals.type]
  implicit val brazierCommandingFireElementalsRW: default.ReadWriter[MagicalItems.BrazierCommandingFireElementals.type] = upickle.default.macroRW[BrazierCommandingFireElementals.type]
  implicit val broomOfFlyingRW: default.ReadWriter[MagicalItems.BroomOfFlying.type] = upickle.default.macroRW[BroomOfFlying.type]
  implicit val censerCommandingAirElementalsRW: default.ReadWriter[MagicalItems.CenserCommandingAirElementals.type] = upickle.default.macroRW[CenserCommandingAirElementals.type]
  implicit val cloakOfDisplacementRW: default.ReadWriter[MagicalItems.CloakOfDisplacement.type] = upickle.default.macroRW[CloakOfDisplacement.type]
  implicit val crystalBallRW: default.ReadWriter[MagicalItems.CrystalBall.type] = upickle.default.macroRW[CrystalBall.type]
  implicit val crystalBallWithClairaudienceRW: default.ReadWriter[MagicalItems.CrystalBallWithClairaudience.type] = upickle.default.macroRW[CrystalBallWithClairaudience.type]
  implicit val drumsOfPanicRW: default.ReadWriter[MagicalItems.DrumsOfPanic.type] = upickle.default.macroRW[DrumsOfPanic.type]
  implicit val efreetiBottleRW: default.ReadWriter[MagicalItems.EfreetiBottle.type] = upickle.default.macroRW[EfreetiBottle.type]
  implicit val elvenBootsRW: default.ReadWriter[MagicalItems.ElvenBoots.type] = upickle.default.macroRW[ElvenBoots.type]
  implicit val elvenCloakRW: default.ReadWriter[MagicalItems.ElvenCloak.type] = upickle.default.macroRW[ElvenCloak.type]
  implicit val flyingCarpetRW: default.ReadWriter[MagicalItems.FlyingCarpet.type] = upickle.default.macroRW[FlyingCarpet.type]
  implicit val gauntletsOfOgrePowerRW: default.ReadWriter[MagicalItems.GauntletsOfOgrePower.type] = upickle.default.macroRW[GauntletsOfOgrePower.type]
  implicit val girdleOfGiantStrengthRW: default.ReadWriter[MagicalItems.GirdleOfGiantStrength.type] = upickle.default.macroRW[GirdleOfGiantStrength.type]
  implicit val helmOfReadingLanguagesAndMagicRW: default.ReadWriter[MagicalItems.HelmOfReadingLanguagesAndMagic.type] = upickle.default.macroRW[HelmOfReadingLanguagesAndMagic.type]
  implicit val helmOfTelepathyRW: default.ReadWriter[MagicalItems.HelmOfTelepathy.type] = upickle.default.macroRW[HelmOfTelepathy.type]
  implicit val helmOfTeleportationRW: default.ReadWriter[MagicalItems.HelmOfTeleportation.type] = upickle.default.macroRW[HelmOfTeleportation.type]
  implicit val hornOfBlastingRW: default.ReadWriter[MagicalItems.HornOfBlasting.type] = upickle.default.macroRW[HornOfBlasting.type]
  implicit val hornOfDoomRW: default.ReadWriter[MagicalItems.HornOfDoom.type] = upickle.default.macroRW[HornOfDoom.type]
  implicit val medallionOfESPRW: default.ReadWriter[MagicalItems.MedallionOfESP.type] = upickle.default.macroRW[MedallionOfESP.type]
  implicit val mirrorOfLifeTrappingRW: default.ReadWriter[MagicalItems.MirrorOfLifeTrapping.type] = upickle.default.macroRW[MirrorOfLifeTrapping.type]
  implicit val ropeOfClimbingRW: default.ReadWriter[MagicalItems.RopeOfClimbing.type] = upickle.default.macroRW[RopeOfClimbing.type]
  implicit val scarabOfProtectionRW: default.ReadWriter[MagicalItems.ScarabOfProtection.type] = upickle.default.macroRW[ScarabOfProtection.type]
  implicit val stoneCommandingEarthElementalsRW: default.ReadWriter[MagicalItems.StoneCommandingEarthElementals.type] = upickle.default.macroRW[StoneCommandingEarthElementals.type]
  implicit val miscellaneousRW: default.ReadWriter[Miscellaneous] = upickle.default.macroRW[Miscellaneous]


  implicit val clairaudienceRW: default.ReadWriter[MagicalItems.Clairaudience.type] = upickle.default.macroRW[Clairaudience.type]
  implicit val clairvoyanceRW: default.ReadWriter[MagicalItems.Clairvoyance.type] = upickle.default.macroRW[Clairvoyance.type]
  implicit val coldResistanceRW: default.ReadWriter[MagicalItems.ColdResistance.type] = upickle.default.macroRW[ColdResistance.type]
  implicit val controlAnimalRW: default.ReadWriter[MagicalItems.ControlAnimal.type] = upickle.default.macroRW[ControlAnimal.type]
  implicit val controlDragonRW: default.ReadWriter[MagicalItems.ControlDragon.type] = upickle.default.macroRW[ControlDragon.type]
  implicit val controlGiantRW: default.ReadWriter[MagicalItems.ControlGiant.type] = upickle.default.macroRW[ControlGiant.type]
  implicit val controlHumanRW: default.ReadWriter[MagicalItems.ControlHuman.type] = upickle.default.macroRW[ControlHuman.type]
  implicit val controlPlantRW: default.ReadWriter[MagicalItems.ControlPlant.type] = upickle.default.macroRW[ControlPlant.type]
  implicit val controlUndeadRW: default.ReadWriter[MagicalItems.ControlUndead.type] = upickle.default.macroRW[ControlUndead.type]
  implicit val delusionPotionRW: default.ReadWriter[MagicalItems.DelusionPotion.type] = upickle.default.macroRW[DelusionPotion.type]
  implicit val diminutionRW: default.ReadWriter[MagicalItems.Diminution.type] = upickle.default.macroRW[Diminution.type]
  implicit val espRW: default.ReadWriter[MagicalItems.ESP.type] = upickle.default.macroRW[ESP.type]
  implicit val fireResistanceRW: default.ReadWriter[MagicalItems.FireResistance.type] = upickle.default.macroRW[FireResistance.type]
  implicit val flyingRW: default.ReadWriter[MagicalItems.Flying.type] = upickle.default.macroRW[Flying.type]
  implicit val gaseousFormRW: default.ReadWriter[MagicalItems.GaseousForm.type] = upickle.default.macroRW[GaseousForm.type]
  implicit val giantStrengthRW: default.ReadWriter[MagicalItems.GiantStrength.type] = upickle.default.macroRW[GiantStrength.type]
  implicit val growthRW: default.ReadWriter[MagicalItems.Growth.type] = upickle.default.macroRW[Growth.type]
  implicit val healing: default.ReadWriter[MagicalItems.Healing.type] = upickle.default.macroRW[Healing.type]
  implicit val heroismRW: default.ReadWriter[MagicalItems.Heroism.type] = upickle.default.macroRW[Heroism.type]
  implicit val invisibilityPotionRW: default.ReadWriter[MagicalItems.InvisibilityPotion.type] = upickle.default.macroRW[InvisibilityPotion.type]
  implicit val invulnerabilityRW: default.ReadWriter[MagicalItems.Invulnerability.type] = upickle.default.macroRW[Invulnerability.type]
  implicit val levitationRW: default.ReadWriter[MagicalItems.Levitation.type] = upickle.default.macroRW[Levitation.type]
  implicit val longevityRW: default.ReadWriter[MagicalItems.Longevity.type] = upickle.default.macroRW[Longevity.type]
  implicit val poisonRW: default.ReadWriter[MagicalItems.Poison.type] = upickle.default.macroRW[Poison.type]
  implicit val speedRW: default.ReadWriter[MagicalItems.Speed.type] = upickle.default.macroRW[Speed.type]
  implicit val treasureFindingRW: default.ReadWriter[MagicalItems.TreasureFinding.type] = upickle.default.macroRW[TreasureFinding.type]
  implicit val potionRW: default.ReadWriter[Potion] = upickle.default.macroRW[Potion]

  implicit val animalControlRW: default.ReadWriter[MagicalItems.AnimalControl.type] = upickle.default.macroRW[AnimalControl.type]
  implicit val delusionRW: default.ReadWriter[MagicalItems.Delusion.type] = upickle.default.macroRW[Delusion.type]
  implicit val djinniSummoningRW: default.ReadWriter[MagicalItems.DjinniSummoning.type] = upickle.default.macroRW[DjinniSummoning.type]
  implicit val earRW: default.ReadWriter[MagicalItems.Ear.type] = upickle.default.macroRW[Ear.type]
  implicit val elementalAdaptationRW: default.ReadWriter[MagicalItems.ElementalAdaptation.type] = upickle.default.macroRW[ElementalAdaptation.type]
  implicit val fireResistanceRingRW: default.ReadWriter[MagicalItems.FireResistanceRing.type] = upickle.default.macroRW[FireResistanceRing.type]
  implicit val holinessRW: default.ReadWriter[MagicalItems.Holiness.type] = upickle.default.macroRW[Holiness.type]
  implicit val humanControlRW: default.ReadWriter[MagicalItems.HumanControl.type] = upickle.default.macroRW[HumanControl.type]
  implicit val invisibilityRW: default.ReadWriter[MagicalItems.Invisibility.type] = upickle.default.macroRW[Invisibility.type]
  implicit val lifeProtectionRW: default.ReadWriter[MagicalItems.LifeProtection.type] = upickle.default.macroRW[LifeProtection.type]
  implicit val memoryRW: default.ReadWriter[MagicalItems.Memory.type] = upickle.default.macroRW[Memory.type]
  implicit val plantControlRW: default.ReadWriter[MagicalItems.PlantControl.type] = upickle.default.macroRW[PlantControl.type]
  implicit val protectionRW: default.ReadWriter[Protection] = upickle.default.macroRW[Protection]
  implicit val quicknessRW: default.ReadWriter[MagicalItems.Quickness.type] = upickle.default.macroRW[Quickness.type]
  implicit val ringRW: default.ReadWriter[Ring] = upickle.default.macroRW[Ring]

  implicit val rodOfCancellationRW: default.ReadWriter[MagicalItems.RodOfCancellation.type] = upickle.default.macroRW[RodOfCancellation.type]
  implicit val snakeStaffRW: default.ReadWriter[MagicalItems.SnakeStaff.type] = upickle.default.macroRW[SnakeStaff.type]
  implicit val staffOfCommandingRW: default.ReadWriter[MagicalItems.StaffOfCommanding.type] = upickle.default.macroRW[StaffOfCommanding.type]
  implicit val staffOfHealingRW: default.ReadWriter[MagicalItems.StaffOfHealing.type] = upickle.default.macroRW[StaffOfHealing.type]
  implicit val staffOfPowerRW: default.ReadWriter[MagicalItems.StaffOfPower.type] = upickle.default.macroRW[StaffOfPower.type]
  implicit val staffOfStrikingRW: default.ReadWriter[MagicalItems.StaffOfStriking.type] = upickle.default.macroRW[StaffOfStriking.type]
  implicit val staffOfWizardryRW: default.ReadWriter[MagicalItems.StaffOfWizardry.type] = upickle.default.macroRW[StaffOfWizardry.type]
  implicit val wandOfColdRW: default.ReadWriter[MagicalItems.WandOfCold.type] = upickle.default.macroRW[WandOfCold.type]
  implicit val wandOfEnemyDetectionRW: default.ReadWriter[MagicalItems.WandOfEnemyDetection.type] = upickle.default.macroRW[WandOfEnemyDetection.type]
  implicit val wandOfFearRW: default.ReadWriter[MagicalItems.WandOfFear.type] = upickle.default.macroRW[WandOfFear.type]
  implicit val wandOfFireballsRW: default.ReadWriter[MagicalItems.WandOfFireballs.type] = upickle.default.macroRW[WandOfFireballs.type]
  implicit val wandOfIllusionRW: default.ReadWriter[MagicalItems.WandOfIllusion.type] = upickle.default.macroRW[WandOfIllusion.type]
  implicit val wandOfLightningBoltsRW: default.ReadWriter[MagicalItems.WandOfLightningBolts.type] = upickle.default.macroRW[WandOfLightningBolts.type]
  implicit val wandOfMagicDetectionRW: default.ReadWriter[MagicalItems.WandOfMagicDetection.type] = upickle.default.macroRW[WandOfMagicDetection.type]
  implicit val wandOfParalyzationRW: default.ReadWriter[MagicalItems.WandOfParalyzation.type] = upickle.default.macroRW[WandOfParalyzation.type]
  implicit val wandOfPolymorphRW: default.ReadWriter[MagicalItems.WandOfPolymorph.type] = upickle.default.macroRW[WandOfPolymorph.type]
  implicit val wandOfSecretDoorDetectionRW: default.ReadWriter[MagicalItems.WandOfSecretDoorDetection.type] = upickle.default.macroRW[WandOfSecretDoorDetection.type]
  implicit val wandOfTrapDetectionRW: default.ReadWriter[MagicalItems.WandOfTrapDetection.type] = upickle.default.macroRW[WandOfTrapDetection.type]
  implicit val wandStaffOrRodRW: default.ReadWriter[WandStaffOrRod] = upickle.default.macroRW[WandStaffOrRod]

  implicit val magicItemRW: default.ReadWriter[MagicItem] = upickle.default.macroRW[MagicItem]

  implicit val equipmentRW: default.ReadWriter[Equipment] = upickle.default.macroRW[Equipment]

  implicit val abundantStepRw: default.ReadWriter[KiPowers.AbundantStep.type] = upickle.default.macroRW[AbundantStep.type]
  implicit val burstingFistRw: default.ReadWriter[KiPowers.BurstingFist.type] = upickle.default.macroRW[BurstingFist.type]
  implicit val deflectArrowsRw: default.ReadWriter[KiPowers.DeflectArrows.type] = upickle.default.macroRW[DeflectArrows.type]
  implicit val diamondBodyRw: default.ReadWriter[KiPowers.DiamondBody.type] = upickle.default.macroRW[DiamondBody.type]
  implicit val diamondFistRw: default.ReadWriter[KiPowers.DiamondFist.type] = upickle.default.macroRW[DiamondFist.type]
  implicit val evasionRw: default.ReadWriter[KiPowers.Evasion.type] = upickle.default.macroRW[Evasion.type]
  implicit val featherBalanceRw: default.ReadWriter[KiPowers.FeatherBalance.type] = upickle.default.macroRW[FeatherBalance.type]
  implicit val featherStepRw: default.ReadWriter[KiPowers.FeatherStep.type] = upickle.default.macroRW[FeatherStep.type]
  implicit val flawlessMindRw: default.ReadWriter[KiPowers.FlawlessMind.type] = upickle.default.macroRW[FlawlessMind.type]
  implicit val improvedEvasionRw: default.ReadWriter[KiPowers.ImprovedEvasion.type] = upickle.default.macroRW[ImprovedEvasion.type]
  implicit val kiStrikeRw: default.ReadWriter[KiPowers.KiStrike.type] = upickle.default.macroRW[KiStrike.type]
  implicit val punishingStrikeRw: default.ReadWriter[KiPowers.PunishingStrike.type] = upickle.default.macroRW[PunishingStrike.type]
  implicit val purityOfBodyRw: default.ReadWriter[KiPowers.PurityOfBody.type] = upickle.default.macroRW[PurityOfBody.type]
  implicit val quiveringPalmRw: default.ReadWriter[KiPowers.QuiveringPalm.type] = upickle.default.macroRW[QuiveringPalm.type]
  implicit val silverFistRw: default.ReadWriter[KiPowers.SilverFist.type] = upickle.default.macroRW[SilverFist.type]
  implicit val slowFallRw: default.ReadWriter[KiPowers.SlowFall.type] = upickle.default.macroRW[SlowFall.type]
  implicit val stunningFistRw: default.ReadWriter[KiPowers.StunningFist.type] = upickle.default.macroRW[StunningFist.type]
  implicit val timelessBodyRw: default.ReadWriter[KiPowers.TimelessBody.type] = upickle.default.macroRW[TimelessBody.type]
  implicit val tongueOfTheStarsRw: default.ReadWriter[KiPowers.TongueOfTheStars.type] = upickle.default.macroRW[TongueOfTheStars.type]
  implicit val wholenessOfBodyRw: default.ReadWriter[KiPowers.WholenessOfBody.type] = upickle.default.macroRW[WholenessOfBody.type]
  implicit val kiPowerRW: default.ReadWriter[KiPower] = upickle.default.macroRW[KiPower]

  implicit val stateRW: default.ReadWriter[CharacterState] =  upickle.default.macroRW[CharacterState]

}
